name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - joaoliveira6704

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please provide as much detail as possible to help us identify and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Launch the application
        2. Connect ESP32 device
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Other Linux
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: qt-version
    attributes:
      label: Qt Version
      description: Which version of Qt are you using?
      placeholder: e.g., Qt 6.5.3
    validations:
      required: true

  - type: input
    id: compiler
    attributes:
      label: Compiler
      description: Which compiler and version?
      placeholder: e.g., GCC 11.4.0, MSVC 2019, Clang 14.0
    validations:
      required: false

  - type: dropdown
    id: hardware
    attributes:
      label: Using ESP32 Hardware?
      description: Are you using actual ESP32 hardware or simulation mode?
      options:
        - "Yes - ESP32 connected"
        - "No - Simulation mode only"
        - "Both - Bug occurs in both modes"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Output / Logs
      description: Please copy and paste any relevant console output or error messages
      render: shell
      placeholder: Paste console output here

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does it happen consistently or intermittently?
        - Did this work in a previous version?
        - Any custom modifications?

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all requested information above
          required: true
        - label: I am using the latest version of Horus Project
          required: false
