name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees:
  - joaoliveira6704

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input to make Horus Project better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        A clear description of what you want to happen.
        Include mockups, diagrams, or examples if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternatives you've thought about

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - "UI/UX - User Interface"
        - "Hardware - ESP32/Sensors"
        - "Instruments - New PFD instruments"
        - "Performance - Speed/Optimization"
        - "Data - Logging/Recording"
        - "Configuration - Settings/Options"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - "High - Critical for my use case"
        - "Medium - Would be very helpful"
        - "Low - Nice to have"
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        When developing UAVs, I need to...
        This would help me by...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples or references from other applications
      placeholder: |
        Similar to how [Other Application] does it...
        Example: [Link or description]

  - type: dropdown
    id: willing
    attributes:
      label: Implementation
      description: Would you be willing to help implement this feature?
      options:
        - "Yes - I can implement this"
        - "Yes - I can help with testing"
        - "Maybe - With guidance"
        - "No - Just suggesting"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature
      placeholder: |
        Technical considerations:
        - Requires Qt 6.x feature X
        - Should work with existing serial protocol

        UI mockup: [attach image]

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and this feature has not been requested
          required: true
        - label: This feature aligns with the project's goals (UAV ground control)
          required: true
        - label: I have provided sufficient detail for evaluation
          required: true
